name: social_share_pro
description: Wide variety of sharing options you'll need to share directly to certain well-known apps.
version: 0.0.1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.application.social_share_pro
        pluginClass: SocialSharePlugin
      ios:
        pluginClass: SocialSharePlugin